package com.nexaerp.notification;

public enum NotificationType {
    SYSTEM,
    USER_INVITATION,
    INVOICE_OVERDUE,
    INVOICE_PAYMENT,
    INVOICE_POSTED,
    INVOICE_CANCELLED,
    VENDOR_BILL_DUE,
    VENDOR_BILL_PAYMENT,
    BUDGET_WARNING,
    BUDGET_EXCEEDED,
    ACCOUNTING_PERIOD,
    EXPENSE,
    RECURRING_EXPENSE,
    PAYMENT,
    BANKING,
    FIXED_ASSET,
    JOURNAL_DRAFT_PENDING,
    RECURRING_EXPENSE_DRAFT_PENDING,
    ACCOUNTING_PERIOD_CLOSED,
    ACCOUNTING_PERIOD_LOCKED
}
