package com.nexaerp.notification;

public enum NotificationType {
    SYSTEM,
    USER_INVITATION,
    INVOICE_OVERDUE,
    INVOICE_PAYMENT,
    VENDOR_BILL_DUE,
    VENDOR_BILL_PAYMENT,
    BUDGET_WARNING,
    BUDGET_EXCEEDED,
    ACCOUNTING_PERIOD,
    EXPENSE,
    RECURRING_EXPENSE,
    PAYMENT,
    BANKING,
    FIXED_ASSET
}
